python3 resnetModel.py  --batch_size=1  --num_workers=0 --output_file='hdf5-batch-1-work-0-thread-0.csv' --num_threads=0
python3 resnetModel.py  --batch_size=1  --num_workers=1 --output_file='hdf5-batch-1-work-1-thread-0.csv' --num_threads=0
python3 resnetModel.py  --batch_size=1  --num_workers=1 --output_file='hdf5-batch-1-work-1-thread-1.csv' --num_threads=1
python3 resnetModel.py  --batch_size=1  --num_workers=2 --output_file='hdf5-batch-1-work-2-thread-2.csv' --num_threads=2
python3 resnetModel.py  --batch_size=1  --num_workers=3 --output_file='hdf5-batch-1-work-3-thread-3.csv' --num_threads=3
python3 resnetModel.py  --batch_size=1  --num_workers=4 --output_file='hdf5-batch-1-work-4-thread-4.csv' --num_threads=4
python3 resnetModel.py  --batch_size=2  --num_workers=0 --output_file='hdf5-batch-2-work-0-thread-0.csv' --num_threads=0
python3 resnetModel.py  --batch_size=2  --num_workers=1 --output_file='hdf5-batch-2-work-1-thread-0.csv' --num_threads=0
python3 resnetModel.py  --batch_size=2  --num_workers=1 --output_file='hdf5-batch-2-work-1-thread-1.csv' --num_threads=1
python3 resnetModel.py  --batch_size=2  --num_workers=2 --output_file='hdf5-batch-2-work-2-thread-2.csv' --num_threads=2
python3 resnetModel.py  --batch_size=2  --num_workers=3 --output_file='hdf5-batch-2-work-3-thread-3.csv' --num_threads=3
python3 resnetModel.py  --batch_size=2  --num_workers=4 --output_file='hdf5-batch-2-work-4-thread-4.csv' --num_threads=4
python3 resnetModel.py  --batch_size=4  --num_workers=0 --output_file='hdf5-batch-4-work-0-thread-0.csv' --num_threads=0
python3 resnetModel.py  --batch_size=4  --num_workers=1 --output_file='hdf5-batch-4-work-1-thread-0.csv' --num_threads=0
python3 resnetModel.py  --batch_size=4  --num_workers=1 --output_file='hdf5-batch-4-work-1-thread-1.csv' --num_threads=1
python3 resnetModel.py  --batch_size=4  --num_workers=2 --output_file='hdf5-batch-4-work-2-thread-2.csv' --num_threads=2
python3 resnetModel.py  --batch_size=4  --num_workers=3 --output_file='hdf5-batch-4-work-3-thread-3.csv' --num_threads=3
python3 resnetModel.py  --batch_size=4  --num_workers=4 --output_file='hdf5-batch-4-work-4-thread-4.csv' --num_threads=4